name: Deploy to Cloudflare Workers
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v5
        with:
          submodules: true      
          fetch-depth: 0
          ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} 
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=surely-vue
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
